// Writes app/scrollbars.css: scrollbars drawn by hand. The thumb is a wobbly
// ballpoint line (two passes, the second lighter), the track a faint pencil
// line down the middle; both are seeded SVGs stretched to the bar, in the
// docs' ink by day and by night. Chrome and Safari only: Firefox keeps its
// own thin bar (see the @supports in app/globals.css).

import { writeFileSync } from "node:fs";
import { parseColor } from "../lib/color.ts";
import { handCurve, hashSeed } from "../registry/ballpoint/lib/ink-sketch.ts";

const toGamma = (c: number) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
const hex = (css: string) =>
  `#${parseColor(css)
    .map((c) => Math.round(Math.min(1, Math.max(0, toGamma(c))) * 255).toString(16).padStart(2, "0"))
    .join("")}`;
const ink = { light: hex("oklch(0.4 0.185 267)"), dark: hex("oklch(0.9 0.045 258)") };

type P = [number, number];
// Bars are 12px across; along them the drawing is stretched, so it only needs to wobble.
const along = (seed: string, centre: number, amp: number, steps = 9): P[] =>
  Array.from({ length: steps + 1 }, (_, i) => {
    const r = (hashSeed(`${seed}-${i}`) % 1000) / 1000 - 0.5;
    return [centre + r * 2 * amp, (i / steps) * 100];
  });

function svg(vertical: boolean, color: string, kind: "thumb" | "track", strong: boolean) {
  const flip = (pts: P[]) => (vertical ? pts : pts.map(([a, b]) => [b, a] as P));
  const line = (seed: string, c: number, amp: number, w: number, o: number) =>
    `<path d='${handCurve(hashSeed(seed), flip(along(seed, c, amp)), { jitter: 0 })}' fill='none' stroke='${color}' stroke-width='${w}' stroke-linecap='round' stroke-linejoin='round' opacity='${o}' vector-effect='non-scaling-stroke'/>`;
  const body =
    kind === "thumb"
      ? line("sb-a", 6, 0.9, 3.2, strong ? 0.95 : 0.7) + line("sb-b", 5.4, 0.8, 1.4, strong ? 0.7 : 0.45)
      : line("sb-t", 6, 0.7, 1, 0.35);
  const box = vertical ? "0 0 12 100" : "0 0 100 12";
  const url = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='${box}' preserveAspectRatio='none'>${body}</svg>`;
  return `url("data:image/svg+xml,${encodeURIComponent(url)}")`;
}

const rule = (vertical: boolean, mode: "light" | "dark") => {
  const pseudo = vertical ? ":vertical" : ":horizontal";
  const c = ink[mode];
  const thumb = (strong: boolean) => `${svg(vertical, c, "thumb", strong)} center / 100% 100% no-repeat`;
  const dark = mode === "dark";
  const selFor = (s: string) => (dark ? `.dark ${s}, .dark${s.startsWith("::") ? s : ` ${s}`}` : s);
  return [
    `${selFor(`::-webkit-scrollbar-track${pseudo}`)} {\n  background: ${svg(vertical, c, "track", false)} center / 100% 100% no-repeat;\n}`,
    `${selFor(`::-webkit-scrollbar-thumb${pseudo}`)} {\n  background: ${thumb(false)};\n}`,
    `${selFor(`::-webkit-scrollbar-thumb${pseudo}:hover`)},\n${selFor(`::-webkit-scrollbar-thumb${pseudo}:active`)} {\n  background: ${thumb(true)};\n}`,
  ].join("\n\n");
};

const css = `/* Generated by scripts/scrollbar-art.ts. Do not edit by hand. */

::-webkit-scrollbar {
  width: 12px;
  height: 12px;
}

::-webkit-scrollbar-corner,
::-webkit-scrollbar-button {
  display: none;
  background: transparent;
}

::-webkit-scrollbar-thumb {
  min-height: 2.5rem;
  min-width: 2.5rem;
  border: 0;
  border-radius: 0;
}

${(["light", "dark"] as const).flatMap((m) => [rule(true, m), rule(false, m)]).join("\n\n")}
`;

writeFileSync(new URL("../app/scrollbars.css", import.meta.url), css);
console.log(`app/scrollbars.css: ${css.length} bytes`);
